### ISSUE TITLE
Compression is destructive operation

### ISSUE THREAD

**Issue by theKashey** [css/csso#296]
i wish to run csso.parse once, and then run csso.compress some times with different usage filters.
Unfortunately .compress (readBlock) will break list of Rules.
Ok - i can copy rules
```
csso.compress({
   type: 'StyleSheet',
    rules: styleAst.rules.copy()
}....
```
But anyway block.stylesheet will be overwritten in next step.

**Comment by lahmatiy** [comment]
Yep, compess() modifies input AST, since AST coping is expensive operation and doesn't needed in most cases. Your solution doesn't solve the problem since you just copy a list but nested AST nodes still the same.

However I caught your use case. Suggestions:
- new option for `compress()` to keep input AST untouched and compress AST copy instead (technically function will copy AST before transforming)
- additionally add a new function `copy()` to make deep copy of AST node

**Comment by theKashey** [comment]
Both variants are usefull. And looks like data "protection" must be enabled by default. And only .minify can run w/o copying data.
Or update documentation with big !!WARNING!!
