### ISSUE TITLE
Font-family broken when !important

### ISSUE THREAD

**Issue by abarre** [css/csso#366]
Before :
```
font-family: FuturaPt-Medium !important;
```
After :
```
font-family: FuturaPt-Medium!important;
```
The space before `!` is missing.

**Comment by lahmatiy** [comment]
The space before `!important` is not required. Is there any browser where it causes to a problem? As I know, all browsers have no issues with that.

**Comment by abarre** [comment]
I will close this issue. I can't reproduce it anymore so I guess the error was something else.
Sorry for the error.

I see that "structural optimization" has a few bugs, so I think that this option is not ready for production. However, do you think that this library with `restructure:false` can already be used in production without known bugs ?

**Comment by lahmatiy** [comment]
Truly speaking, all CSS minifiers have a structural optimisations bugs due to its complication (some bugs may not be discovered yet). In most cases it's not an issue. If you're worry about possible problems, you can switch off that feature.
I'm personally using CSSO in all projects I participate in production. Of cause, my experience may be irrelevant, since as much depends on CSS practices in use.
