### ISSUE TITLE
How to install directly without npm & use as php library

### ISSUE THREAD

**Issue by nabtron** [css/csso#386]
Is there a way to simply copy a folder of CSSO and call it from my code to combine & minify css files in my project by sending them to it?

**Comment by nabtron** [comment]
I need to use it in my PHP project. So is there a way to use it as a library?

**Comment by lahmatiy** [comment]
CSSO can't be used as PHP library since written in JavaScript (but you can use a JS->PHP transpiler if such exists). You can download sources of repo via a link on releases (see [assets](https://github.com/css/csso/releases/tag/v3.5.0)). To use CSSO from PHP, you can run it as a console command using [csso-cli](https://github.com/css/csso-cli) (you need to spawn a process and node.js must be available in env). csso-cli able to minify a single file, if you need to combine files in a single one you should do it by yourself.
