### ISSUE TITLE
usage with webpack as es module 

### ISSUE THREAD

**Issue by selul** [css/csso#451]
hi, 

I'm trying to use csso library with webpack as es module. The entry file is: 
```js
import { minify } from "csso";
```
and on the output file, I get 

```js
const version_require = (0,external_module_namespaceObject.createRequire)("file:///<path>/node_modules/.pnpm/csso@5.0.2/node_modules/csso/lib/version.js");
```
which throws an error since versions.js is not present in the final build. 
 
Any idea what could be wrong? I see that version.js is not used in the internal library code but since this package.json is not using `sideEffects:false` the tree shaking mechanism will still include this in the final build.

Also, I would like to mention that the version before 5.0 is working fine, so it might be something related to the dual build mechanism implemented in 5.0.

Any help is appreciated.

**Comment by selul** [comment]
Thanks a lot for the insights, from checking my webpack config I don't do anything in particular that could affect browser config. 

```js
{
    externals: {
        "aws-sdk": "aws-sdk"
    },
    optimization: {
        minimize: false,
    },
    externalsType: "node-commonjs",
    mode: "production",
    stats: "minimal",
    target: "node14",
    watch: false, 
    experiments: {
        outputModule: true,
    },
    devtool: "inline-cheap-module-source-map", 
    output: {
        module: true,
        library: {
            type: "module",
        },
        filename: "index.mjs",
        path: resolve( "./dist/" ),
    }
};
```

As for the `package.json` the only thing that is related to this is having: 
```json
 "sideEffects": false,
 "type": "module",
```

**Comment by lahmatiy** [comment]
Thank you for sharing your webpack config. I tried it with (latest versions):
```
webpack: 5.70.0
webpack-cli: 4.9.2
```
And bundle seems to work (no exceptions). I suppose, the problem is connected with `target: "node14"` which is disabling usage of `browser` field in `package.json`.

You also could try:
- add `resolve: { aliasFields: ["browser"] }` – it will enable `browser` field usage
- to import `"csso/dist/csso.esm"` instead of `"csso"` – however, its minified
- add `module` to `externals`, probably your webpack version doesn't track it as external (not sure it works)
- try latest webpack version

**Comment by selul** [comment]
Thanks a lot for feedback, adding `resolve: { aliasFields: ["browser"] }` solved the issue.
