### ISSUE TITLE
Отладочный режим

### ISSUE THREAD

**Issue by kizu** [css/csso#9]
Очень хочется режим, с которым кроме результата будет выдаваться статистика о том что именно было прооптимизированно:
— какие свойства были удалены как перекрытые;
— какие именно оптимизации оказались самыми эффективными;
Ну и всё в том же духе.
Помимо практической пользы (можно, например, искать где что перекрывается) было бы просто забавно смотреть на статистику по тому какие методы оптимизации какой прирост дают :)

**Comment by lahmatiy** [comment]
CSSO cli has [`--debug`](https://github.com/css/csso#debugging) option that can to show details about each step transformation. Not so good for large files, but can helps with isolated issue.
Since 1.6 CSS parse error are much verbose. It should be much easier to find out what problem is. And source maps can help now as well.
